import {
  EasySideImg,
  Product1BannerImg,
  Product1BannerPhoneImg,
  Product1Img1,
  Product2BannerImg,
  Product2BannerPhoneImg,
  Product2Img,
  UniqueSideImg,
  Product4BannerImg,
  Product4Img,
  TrimWoodBg1,
  LineaVerticaImg1,
  LineaVerticaImg2,
  LineaVerticaImg3,
  LineaVerticaShade1,
  LineaVerticaShade2,
  LineaVerticaShade3,
  LineaLouverImg1,
  LineaLouverImg2,
  LineaLouverImg3,
  LineaLouverShade1,
  LineaLouverShade2,
  LineaLouverShade3,
  LineaSoffitImg1,
  LineaSoffitImg2,
  LineaSoffitImg3,
  LineaSoffitShade1,
  LineaSoffitShade3,
  LineaDuoImg1,
  LineaDuoImg2,
  LineaDuoImg3,
  LineaDuoShade1,
  LineaDuoShade2,
  LineaDuoShade3,
  DuraNormaImg1,
  DuraNormaImg2,
  DuraNormaImg3,
  DuraNormaShade1,
  DuraNormaShade2,
  DuraNormaShade3,
  DuraStrettaImg1,
  DuraStrettaImg2,
  DuraStrettaImg3,
  DuraStrettaShade1,
  DuraStrettaShade2,
  DuraStrettaShade3,
  EasyLineaImg1,
  EasyLineaImg2,
  EasyLineaImg3,
  EasyLineaShade1,
  EasyLineaShade2,
  EasyLineaShade3,
  EasyPyramidImg1,
  EasyPyramidImg2,
  EasyPyramidImg3,
  EasyPyramidShade1,
  EasyPyramidShade2,
  EasyPyramidShade3,
  Innov2WaveImg1,
  Innov2WaveImg2,
  Innov2WaveImg3,
  Innov2WaveShade1,
  Innov2WaveShade2,
  Innov2WaveShade3,
  LineaSoffitShade2,
} from '@/utils/assets';

export const productsData = {
  2: {
    bannerSection: {
      bannerPhoneImg: Product1BannerPhoneImg,
      bannerImg: Product1BannerImg,
      headText: 'PARE INDIA BRINGS TO YOU',
      mainText: 'FIRST TIME IN THE WORLD',
    },
    section1data: {
      mainImage: Product1Img1,
      sideImage: EasySideImg,
      techName: 'EASY+ TECHNOLOGY',
      techDesc:
        'This technology ensures quick, dust and dirt free installations. This technology ensures quick, dust and dirt free installations.',
      variants: 3,
    },
    section2data: [
      {
        type: 'Linea',
        desc: '- Transform your space into a masterpiece with Linea Shape Wall Panels. Embrace the art of elegant design as sleek lines harmonize, creating a stunning backdrop that captures the essence of modern sophistication.',
        highlights: ['Easy to install', 'Recyclable', 'Advance Interlocking'],
        productImgs: [EasyLineaImg1, EasyLineaImg2, EasyLineaImg3],
        productShades: [EasyLineaShade1, EasyLineaShade2, EasyLineaShade3],
        pageLink: '/linea',
      },
      {
        type: 'Pyramid',
        desc: "- Transform your space with the timeless allure of pyramid shape wall panels, where geometric elegance converges with architectural intrigue, igniting a symphony of form and function that captivates the eye. Let each panel's meticulously crafted angles and shadows breathe life into your surroundings, showcasing the boundless potential of geometric artistry.",
        highlights: [
          'Easy to install',
          'Anti-bacterial',
          'Termite Proof & Rust Proof',
        ],
        productImgs: [EasyPyramidImg1, EasyPyramidImg2, EasyPyramidImg3],
        productShades: [
          EasyPyramidShade1,
          EasyPyramidShade2,
          EasyPyramidShade3,
        ],
        pageLink: '/pyramid',
      },
      {
        type: 'Arch',
        desc: '- Designed to prioritize a streamlined and straightforward structure, seamlessly integrating them into the EASY+ System. The circular shape of the panels not only adds visual appeal but also plays a critical role in enhancing the overall aesthetic and functionality.',
        highlights: [
          'Easy to install',
          'Advance Interlocking',
          'No Ply required',
        ],
        productImgs: [EasyLineaImg1, EasyLineaImg2, EasyLineaImg3],
        productShades: [EasyLineaShade1, EasyLineaShade2, EasyLineaShade3],
        pageLink: '/arch',
      },
    ],
  },
  3: {
    bannerSection: {
      bannerPhoneImg: Product2BannerPhoneImg,
      bannerImg: Product2BannerImg,
      headText: 'PARE INDIA BRINGS TO YOU',
      mainText: 'FIRST TIME IN INDIA',
    },
    section1data: {
      mainImage: Product2Img,
      sideImage: UniqueSideImg,
      techName: 'DURA+ TECHNOLOGY',
      techDesc:
        'Dura+ is the epitome of strength and durability for your exterior facade needs. With its robust construction and weather-resistant properties, Dura+ offers long-lasting protection and stunning aesthetics.',
      variants: 2,
    },
    section2data: [
      {
        type: 'Norma',
        desc: '- panels make you experience the perfect blend of durability and aesthetics with Norma. These decorative panels are meticulously crafted to provide a long-lasting solution for your exterior facades.',
        highlights: ['Superior Quality', 'Long Life', 'UV Resistant'],
        productImgs: [DuraNormaImg1, DuraNormaImg2, DuraNormaImg3],
        productShades: [DuraNormaShade1, DuraNormaShade2, DuraNormaShade3],
        pageLink: '/norma',
      },
      {
        type: 'Stretta',
        desc: '- panels help you achieve a flawless and refined look for your exterior wall cladding with Stretta. These panels boast a smooth and resilient surface, engineered to withstand scratches and impacts.',
        highlights: [
          'High Impact Resistance',
          'Recyclable',
          'Termite Proof & Rust Proof',
        ],
        productImgs: [DuraStrettaImg1, DuraStrettaImg2, DuraStrettaImg3],
        productShades: [
          DuraStrettaShade1,
          DuraStrettaShade2,
          DuraStrettaShade3,
        ],
        pageLink: '/stretta',
      },
    ],
  },
  1: {
    bannerSection: {
      bannerPhoneImg: Product1BannerPhoneImg,
      bannerImg: Product1BannerImg,
      headText: 'PARE INDIA BRINGS TO YOU',
      mainText: 'FIRST TIME IN INDIA',
    },
    section1data: {
      mainImage: Product1Img1,
      sideImage: UniqueSideImg,
      techName: 'INNOV+ TECHNOLOGY',
      techDesc:
        'Experience transformative spaces with Innov+, the ultimate wall and ceiling system. Enhance aesthetics and functionality seamlessly with cutting-edge innovation. Elevate your space and embrace the future of interior design.',
      variants: 4,
    },
    section2data: [
      {
        type: 'Duo',
        desc: 'an ingenious ceiling and wall system that celebrates the beauty of contrast. By combining two distinct materials, textures, or colours, Duo adds a captivating visual depth that sets it apart from conventional panels. Let your imagination run wild as you mix and match, creating personalized patterns and designs that transform your interiors into a work of art.',
        highlights: ['Unique Interlocking', 'Fire Retardant', 'Light Weight'],
        productImgs: [LineaDuoImg1, LineaDuoImg2, LineaDuoImg3],
        productShades: [LineaDuoShade1, LineaDuoShade2, LineaDuoShade3],
        pageLink: '/duo',
      },
      {
        type: 'Soffit',
        desc: 'an innovative wall and ceiling panel that exudes modern sophistication. Its seamless integration creates a sleek and clean look, while its versatility allows for concealed lighting and air conditioning, adding both function and style to any room. Embrace the beauty of minimalist design with Soffit, as it effortlessly complements any interior theme.',
        highlights: ['No VOC Emission', 'Waterproof', 'Real Wood Feel'],
        productImgs: [LineaSoffitImg1, LineaSoffitImg2, LineaSoffitImg3],
        productShades: [
          LineaSoffitShade1,
          LineaSoffitShade2,
          LineaSoffitShade3,
        ],
        pageLink: '/soffit',
      },
      {
        type: 'Louvers',
        desc: 'a captivating wall and ceiling panel that brings a touch of architectural artistry to your living spaces. These adjustable slats not only create a dynamic visual appeal but also enable precise control over light and airflow, ensuring a comfortable and well-lit ambiance. Let Louvers redefine your interiors by infusing a harmonious blend of aesthetics and functionality.',
        highlights: ['Fire Retardant', 'Maintenance Free', '10 Years Warranty'],
        productImgs: [LineaLouverImg1, LineaLouverImg2, LineaLouverImg3],
        productShades: [
          LineaLouverShade1,
          LineaLouverShade2,
          LineaLouverShade3,
        ],
        pageLink: '/louvers',
      },
      {
        type: 'Vertica',
        desc: 'an avant-garde wall and ceiling panel designed to make a striking statement. Its vertical orientation accentuates the height of your space while adding a sense of grandeur. Crafted from premium materials, Vertica offers a wide range of customizable options, enabling you to curate a space that reflects your unique style and refined taste.',
        highlights: [
          'Sleek Design',
          'Impact Resistance',
          'Unique Interlocking',
        ],
        productImgs: [LineaVerticaImg1, LineaVerticaImg2, LineaVerticaImg3],
        productShades: [
          LineaVerticaShade1,
          LineaVerticaShade2,
          LineaVerticaShade3,
        ],
        pageLink: '/vertica',
      },
    ],
  },
  4: {
    bannerSection: {
      bannerPhoneImg: Product4BannerImg,
      bannerImg: Product4BannerImg,
      headText: 'PARE INDIA BRINGS TO YOU',
      mainText: 'FIRST TIME IN THE WORLD',
    },
    section1data: {
      mainImage: Product4Img,
      sideImage: UniqueSideImg,
      techName: 'INNOV2+ TECHNOLOGY',
      techDesc:
        'Presenting Innov2+, an extraordinary fusion of innovation and excellence, poised to revolutionize your spaces with contemporary elegance and state-of-the-art functionality.',
      variants: 5,
    },
    section2data: [
      {
        type: 'Wave',
        desc: 'panels inspired by the graceful movement of ocean waves, these innovative panels add a touch of elegance and sophistication to any interior surfaces.',
        highlights: ['No VOC Emission', 'Real Wood Look', 'Seamless Look'],
        productImgs: [Innov2WaveImg1, Innov2WaveImg2, Innov2WaveImg3],
        productShades: [Innov2WaveShade1, Innov2WaveShade2, Innov2WaveShade3],
        pageLink: '/wave',
      },
      {
        type: 'Dome',
        desc: 'In the world of interior design, where each element plays a crucial role in shaping the ambiance of a space, Dome-inspired wall panels stand out as a testament to sophistication and timeless beauty.',
        highlights: ['No VOC Emission', 'Waterproof', 'Fire Retardant'],
        productImgs: [Innov2WaveImg1, Innov2WaveImg2, Innov2WaveImg3],
        productShades: [Innov2WaveShade1, Innov2WaveShade2, Innov2WaveShade3],
        pageLink: '/dome',
      },
      {
        type: 'Stripes',
        desc: 'Stripes wall panels stand as a testament to urban elegance and architectural wonder. Drawing inspiration from the iconic shapes of skyscrapers, these panels invite you to immerse yourself in the urban majesty of soaring structures.',
        highlights: ['Waterproof', 'Fire Retardant', '10 Year Warranty'],
        productImgs: [Innov2WaveImg1, Innov2WaveImg2, Innov2WaveImg3],
        productShades: [Innov2WaveShade1, Innov2WaveShade2, Innov2WaveShade3],
        pageLink: '/stripes',
      },
      {
        type: 'Prism',
        desc: 'wall panels stand as a celebration of nature\'s rugged beauty. Inspired by the majestic peaks and valleys of mountain ranges, these panels invite you to embrace the splendor of nature within the comfort of your home.',
        highlights: ['Waterproof', 'Fire Retardant', '10 Year Warranty'],
        productImgs: [Innov2WaveImg1, Innov2WaveImg2, Innov2WaveImg3],
        productShades: [Innov2WaveShade1, Innov2WaveShade2, Innov2WaveShade3],
        pageLink: '/prism',
      },
      {
        type: 'Unic',
        desc: 'Square Wave collection emerges as a bold and captivating choice. Drawing inspiration from the mesmerizing allure of the Unicorn Square Wave, these wall panels bring a touch of magic and rhythmic innovation to your living space.',
        highlights: ['Waterproof', 'Fire Retardant', '10 Year Warrranty'],
        productImgs: [Innov2WaveImg1, Innov2WaveImg2, Innov2WaveImg3],
        productShades: [Innov2WaveShade1, Innov2WaveShade2, Innov2WaveShade3],
        pageLink: '/unic',
      },
      
    ],
  },
};

// Blog Data
export const blogData = [
  {
    title: '5 Creative Ways to Incorporate Tiles into Your Interior Design',
    image: TrimWoodBg1,
    isRed: true,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 1,
  },
  {
    title: 'Expert Tips from Our Design Team',
    image: TrimWoodBg1,
    isRed: true,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 2,
  },
  {
    title:
      'From Bold Patterns to Subtle Textures: Exploring the Versatility of Interior Design Tiles',
    image: TrimWoodBg1,
    isRed: true,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 3,
  },
  {
    title:
      'Revamp Your Home with Unique and Beautiful Tile Designs: Our Top Picks',
    image: TrimWoodBg1,
    isRed: false,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 4,
  },
  {
    title: "Tile Trends 2023: What's Hot and What's Not in Interior Design",
    image: TrimWoodBg1,
    isRed: true,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 5,
  },
  {
    title: "Tile Trends 2023: What's Hot and What's Not in Interior Designs",
    image: TrimWoodBg1,
    isRed: false,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 6,
  },
  {
    title: "Tile Trends 2023: What's Hot and What's Not in Interior Designss",
    image: TrimWoodBg1,
    isRed: true,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 7,
  },
  {
    title: "Tile Trends 2023: What's Hot and What's Not in Interior Designsss",
    image: TrimWoodBg1,
    isRed: false,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 8,
  },
  {
    title: '5 Creative Ways to Incorporate Tiles into Your Interior Designsss',
    image: TrimWoodBg1,
    isRed: true,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 9,
  },
  {
    title: 'Expert Tips from Our Design Teams',
    image: TrimWoodBg1,
    isRed: true,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 10,
  },
  {
    title:
      'From Bold Patterns to Subtle Textures: Exploring the Versatility of Interior Dessign Tiles',
    image: TrimWoodBg1,
    isRed: true,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 11,
  },
  {
    title:
      'Revamp Your Home with Unique and Beautiful Tile Designs: Our Top Piicks',
    image: TrimWoodBg1,
    isRed: false,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 12,
  },
  {
    title: "Tile Trends 2023: What's Hot and What's Not in Interior Deesign",
    image: TrimWoodBg1,
    isRed: true,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 13,
  },
  {
    title: "Tile Trends 2023: What's Hot and What's Not in Interior Dessign",
    image: TrimWoodBg1,
    isRed: false,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 14,
  },
  {
    title: "Tile Trends 2023: What's Hot and What's Not in Innterior Design",
    image: TrimWoodBg1,
    isRed: false,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 15,
  },
  {
    title: "Tile Trends 2023: What's Hot and What's Not in Intterior Design",
    image: TrimWoodBg1,
    isRed: false,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 16,
  },
  {
    title: "Tile Trends 2023: What's Hot and What's Not in Inteerior Design",
    image: TrimWoodBg1,
    isRed: false,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 17,
  },
  {
    title: "Tile Trends 2023: What's Hot and What's Not in Interiior Design",
    image: TrimWoodBg1,
    isRed: true,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 18,
  },
  {
    title: "Tile Trends 2023: What's Hot and What's Not in Interiorrr Design",
    image: TrimWoodBg1,
    isRed: false,
    issuedBy: 'Pare India 2023',
    month: 'May 2023',
    id: 19,
  },
];

export const points = {
  interlock: {
    title: 'Unique Interlocking',
    desc: 'One-of-a-kind interlocking system, ensuring a secure and tight fit.',
  },
  waterproof: {
    title: 'Waterproof',
    desc: 'Built to endure the toughest conditions with superior water resistance.',
  },
  no_voc: {
    title: 'No VOC Emission',
    desc: 'A greener future with our innovative wall panels, boasting no VOC emissions.',
  },
  realwood: {
    title: 'Real Wood Feel',
    desc: 'Achieve the timeless elegance of real wood without compromising on durability.',
  },
  fire_retardant: {
    title: 'Fire Retardant',
    desc: 'Designed to prioritize safety without compromising on style. ',
  },
  free_maintainance: {
    title: 'Maintenance Free',
    desc: 'Simplify your life with our maintenance-free wall and Ceiling systems.',
  },
  warranty: {
    title: '10 Years Warranty',
    desc: 'Our quality panels a worry-free decade of reliable performance and durability.',
  },
  recycle: {
    title: 'Recyclable',
    desc: 'A sustainable solution that combines style and environmental consciousness.',
  },
  easy_to_install: {
    title: 'Easy to install',
    desc: 'Transform your space effortlessly with our easy-to-install wall panel system.',
  },
  anti_bacterial: {
    title: 'Anti-bacterial',
    desc: 'Specifically engineered to inhibit the growth of harmful bacteria.',
  },
  termite_proof: {
    title: 'Termite Proof & Rust Proof',
    desc: 'Fortified with a dual-layer defence, making them impervious to both termites and rust.',
  },
  no_ply: {
    title: 'No Ply required',
    desc: 'Panels that Can Be Screwed Directly onto the walls.',
  },
  light_weight: {
    title: 'Light Weight',
    desc: 'the perfect balance of strength and convenience with our lightweight wall panels.',
  },
};
export const blogsCount = blogData.length;
